Epic login component
wolox-training/lm-android pull request #1
Opened 2018-02-26 15:42 UTC by lmiotti

### Summary
Wolox logo and cover added, email and password edit text added, Sign Up and Log in buttons added and Terms and conditions link to google site

### Screenshot
![image](https://user-images.githubusercontent.com/36635668/36679620-6ae77406-1af2-11e8-85a3-2135ff876d53.png)

### Trello Card
https://trello.com/c/bjzWlmHG/18-u1-frontend-login-componentes-b%C3%A1sicos

2018-02-28 16:16 UTC, DemianIac requested changes
Just a few minor changes . Great work!

2018-02-28 16:16 UTC, DemianIac commented on app/src/main/res/layout/fragment_login.xml
> +    android:padding="1dp"
We should send all the dimens to dimens.xml file :)

2018-02-28 16:16 UTC, DemianIac commented on app/src/main/res/layout/fragment_login.xml
> +        android:layout_marginTop="64dp"
Same here with dimens

2018-02-28 16:16 UTC, DemianIac commented on app/src/main/res/layout/fragment_login.xml
> +        android:layout_marginRight="16dp"
More dimens :3

2018-02-28 16:16 UTC, DemianIac commented on app/src/main/res/values/strings.xml
> +    <string name="login_login">LOG IN</string>
You can write the text like Log in and then set the uppercase to the button . Then you can use the same string resource in other components :)

2018-03-02 16:28 UTC, lmiotti commented
### Summary
Dimens.xml file was created, and dimensions in fragment_layout was referenced to that file.

### Screenshot

![image](https://user-images.githubusercontent.com/36635668/36908583-65a636f0-1e1a-11e8-8fe5-3e55d028a2d5.png)

### Trello Card

https://trello.com/c/bjzWlmHG/18-u1-frontend-login-componentes-b%C3%A1sicos

2018-03-05 15:38 UTC, DemianIac approved these changes
:+1:

2018-03-05 15:46 UTC, merged