Epic login component validate navigation
wolox-training/lm-android pull request #3
Opened 2018-03-02 16:43 UTC by lmiotti

### Summary
Sign up fragment was created. Terms and conditions linked to Wolox website. Some fixes were done when calling to another activity.

### Screenshot
![image](https://user-images.githubusercontent.com/36635668/36910337-2df1523a-1e1f-11e8-8e94-b2be7efe27f2.png)

### Trello Card
https://trello.com/c/qJsqeb7I/20-u1-frontend-login-navegaci%C3%B3n

2018-03-05 16:21 UTC, DemianIac requested changes
Some minor changes ! :smiley:

2018-03-05 16:21 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/training/ui/RootActivity.java
> +            logInIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
You can write more than one flag like this too 
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);

2018-03-05 16:21 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/training/ui/login/LogInFragment.java
> +                    SharedPreferences sharedPref = getActivity().getSharedPreferences(USER, Context.MODE_PRIVATE);
We should send this to the presenter

2018-03-05 16:21 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/training/ui/login/LogInFragment.java
> +                if (!android.util.Patterns.EMAIL_ADDRESS.matcher(mEmailTxt.getText()).matches()) {
Try to make new methods for this like  !isValidEmail(mailText) . You nerver know when the implementation could change :3

2018-03-05 16:21 UTC, DemianIac commented on app/src/main/res/layout/fragment_home.xml
> +        android:text="HOME"/>
Get used to set strings in Strings.xml. Just to get a good muscle memory :muscle: :stuck_out_tongue:

2018-03-05 16:21 UTC, DemianIac commented on app/src/main/res/layout/fragment_login.xml
> +        android:textSize="18sp"
Hardcode dimen . Remember to use dimens.xml

2018-03-05 16:21 UTC, DemianIac commented on app/src/main/res/layout/fragment_login.xml
> +        android:textSize="18sp"
Same here and in the next 3 items

2018-03-05 16:21 UTC, DemianIac commented on app/src/main/res/layout/fragment_signup.xml
> +<?xml version="1.0" encoding="utf-8"?>
Check Hardcode dimens in all this file please :smiley:

2018-03-05 18:11 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/training/ui/login/LogInFragment.java
> +                    SharedPreferences sharedPref = getActivity().getSharedPreferences(USER, Context.MODE_PRIVATE);
Saving key values and calling HomeActivity is sent to Presenter in new version "epic-login-component-validate-navigation-access"

2018-03-05 18:12 UTC, lmiotti commented
### Summary
Harcoded dimens solved, HOME string is referenced to Strings.xml, and FLAGS are rewritten in one line.

### Screenshot
![image](https://user-images.githubusercontent.com/36635668/36991771-852ea8bc-2087-11e8-99b3-9a2f95c47069.png)

### Trello Card
https://trello.com/c/qJsqeb7I/20-u1-frontend-login-navegaci%C3%B3n

2018-03-13 16:53 UTC, DemianIac approved these changes
:+1:

2018-03-14 15:57 UTC, merged