Epic login component validate navigation access
wolox-training/lm-android pull request #4
Opened 2018-03-08 17:32 UTC by lmiotti

### Summary
Communication to REST server stablished and email validation created. 
RootActivty calls Log In activty if non user has loged in.
If email user doesn't exists, token with "No valid user name" is displayed"
If password doesn't match with server information "Password error" token is displayed
If the correct information is set, a "Log in succesfully" token is shown and a progress bar is appears until HomeActivity is called.

### Screenshot
![image](https://user-images.githubusercontent.com/36635668/37166272-62bec8cc-22dd-11e8-9d48-09e8a67ff830.png)

### Trello Card
https://trello.com/c/mUS9sH08/28-u2-backend-login

2018-03-13 16:57 UTC, DemianIac requested changes

2018-03-13 16:57 UTC, DemianIac commented on app/src/main/java/ar/com/wolox/android/training/ui/login/LogInFragment.java
> +        SharedPreferences sharedPref = getActivity().getSharedPreferences(USER, Context.MODE_PRIVATE);
We should save the user in the presenter .

2018-03-14 15:46 UTC, lmiotti commented
### Summary
User key-values passed from LogInFragment to LogInPresenter.

### Screenshot
![image](https://user-images.githubusercontent.com/36635668/37413312-8452a13c-2785-11e8-9741-a00481f1ce32.png)

### Trello Card
https://trello.com/c/mUS9sH08/28-u2-backend-login

2018-03-14 17:34 UTC, DemianIac approved these changes
:+1:

2018-03-14 18:12 UTC, merged